# Generated by Django 4.2 on 2023-04-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="checked",
            new_name="done",
        ),
        migrations.AddField(
            model_name="todo",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
